### PR TITLE
Add -h flag for fisheries harvest .prm file


### PR DESCRIPTION
**Pull request by douglatornell**
re: issue #3

### CODE REVIEW

**Review by raishalovindeer — APPROVED** [review]
Thanks Doug. This looks good to me, and I see that I should use the _harvest_  name key for the -h flag, which is what I want.

**Comment by douglatornell** [comment]
Because the harvest file is a `.prm` file, the implementation is a little different (and slightly simpler) than for species migrations. The files in the `parameters:` section of the YAML file get handled by a loop. So, I set things up so that you add a line like:
```yaml
harvest: /ocean/$USER/Atlantis/salish-sea-atlantis-model/SS_harvest.prm
```
to the `parameters:` section. Order doesn't matter, but I put it below `biology:` in the example YAML.

The file name on the right can be anything you want. In the run and results directories the file will be called `harvest.prm`. I can change that to something else if you want.

Per your comment yesterday, once we merge this there will have to be a harvest item in every YAML file you run, and you will have to control whether or not it is used in your `run.prm` file. That is because the command to run Atlantis in the `Atlantis.sh` file will always include `-h harvest.prm`.

**Comment by douglatornell** [comment]
If you want to test this before I merge the PR, you can. It will involve a bit of git branch switching. I'm happy to talk you through it.

Or, I can go ahead and merge, and deal with anything that I messed up when you find it.

Your choice...

**Comment by raishalovindeer** [comment]
So it seems there is an additional file that is needed when running with fisheries turned on. I got the following error in Atlantis:

> ERROR. Util_Read_Fisheries_XML: Trying to read in the fishery definition file, but no file was provided.
> 
>  See the -q option below.
>
> Util_Usage: atlantis -i input.nc dump -o output.nc -r run.prm -f force.prm -p physics.prm -b biology.prm -m migration.csv -h harvest.prm -a assess.prm -e economics.prm -s functionGroupFile.xml **-q fisheries.xml** [-d destinationFolder] [-t inputFolder]

Looking into the salish-sea-atlantis-model repo I see a `fisheries.csv` file that was added in May this year. I suspect we need to include that (the notation for Atlantis says `.xml`, but note that our fisheries file is actually `.csv`)

**Comment by douglatornell** [comment]
Okay. I'll add `fisheries.csv` in the same way that we have species migrations (another "top level" line in the YAML). I can't do it in the `parameters:` section because the loop that is used for those files forces them copied as `.prm` files. I think it would be chaotic-evil to have `fisheries.csv` turn into `fixheries.prm` :smiling_imp:

**Comment by raishalovindeer** [comment]
😄  I concur.

**Comment by douglatornell** [comment]
Ready for another test!

`git pull` should pull in the new commit on this branch.

Add a line like:
```yaml
fisheries: /ocean/$USER/Atlantis/salish-sea-atlantis-model/SalishFisheries.csv
```
below the `migrations:` line in your YAML file (though order doesn't matter), and let's see how much farther it gets.

**Comment by raishalovindeer** [comment]
Done. The test simulation is off and running, having found all the required flags and files. From the output, I can see that Atlantis is reading parameters from the harvest file, so we have success!

**Comment by douglatornell** [comment]
You can do:
```
git switch main
git pull
git branch -d harvest-flag
```
to get back to the `main` branch, pull in the changes in this PR that have now been merged there, and delete the now irrelevant `harvest-flag` local branch in your workspace.

**Pull request merged**
